# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import django
sys.path.insert(0, os.path.abspath('.'))
django_version = ".".join(map(str, django.VERSION[0:2]))
python_version = ".".join(map(str, sys.version_info[0:2]))
os.environ['DJANGO_SETTINGS_MODULE'] = 'News_Aggregator.settings'
django.setup()

# -- Project information -----------------------------------------------------

project = 'All in one News Aggregator Website'
copyright = '2021, Habesha'
author = 'Habesha'

# The full version, including alpha/beta/rc tags
release = '1.1'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
# +    'sphinxcontrib.apidoc',   # runs sphinx-apidoc automatically as part of sphinx-build
    'sphinx.ext.autodoc',     # the autodoc extensions uses files generated by apidoc
# +    'sphinxcontrib_django',   # does some nicer django autodoc formatting, but:
                             # https://github.com/edoburu/sphinxcontrib-django/issues/12
    'sphinx.ext.viewcode',    # enable viewing autodoc'd code
    'sphinx.ext.intersphinx', # make links between different sphinx-documented packages
    'sphinx.ext.todo',        # TODO: figure out how to use this;-)
# +    'sphinx_markdown_tables', # CommonMark doesn't do tables: This extensions does!
# +    'sphinxcontrib.confluencebuilder', # supposedly installs docs on Confluence
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']